"""Dependency-file consistency checks: runtime input (`requirements.in`) vs. its lock
(`requirements.txt`), and dev/CI input (`requirements-dev.in`) vs. its lock
(`requirements-dev.txt`). Catches: a direct dependency declared in an `.in` file but missing
from its `.txt` lock (would mean CI is silently relying on an undeclared transitive pin), a
lock file that lost its documented "how to regenerate me" header (usually means it was
hand-edited instead of regenerated), and a package pinned to two different versions across
the runtime and dev/CI locks (`requirements-dev.in`'s `-c requirements.txt` constraint is
supposed to prevent this at generation time -- this re-checks it holds at read time too, so
a manual edit to either `.txt` file can't silently reintroduce the drift).

Run from the repository root: `python -m scripts.ci.check_dependency_consistency`.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

_DIRECT_NAME_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)")
_LOCKED_NAME_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*(?:\[[^\]]+\])?)==([^\s;]+)")


def normalize(name: str) -> str:
    """PEP 503 style normalization, so e.g. `python_dotenv`/`python-dotenv`/`Python.Dotenv`
    all compare equal."""
    return re.sub(r"[-_.]+", "-", name).lower()


def direct_names(input_path: Path) -> set[str]:
    names = set()
    for raw_line in input_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "-c", "-r")):
            continue
        match = _DIRECT_NAME_RE.match(line)
        if match:
            names.add(normalize(match.group(1).split("[")[0]))
    return names


def locked_versions(lock_path: Path) -> dict[str, str]:
    versions: dict[str, str] = {}
    for raw_line in lock_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = _LOCKED_NAME_RE.match(line)
        if match:
            versions[normalize(match.group(1).split("[")[0])] = match.group(2)
    return versions


def check_pair(input_path: Path, lock_path: Path, *, expected_header_substring: str, repo_root: Path = REPO_ROOT) -> list[str]:
    errors = []
    if not input_path.exists():
        return [f"{input_path.relative_to(repo_root)} does not exist"]
    if not lock_path.exists():
        return [f"{lock_path.relative_to(repo_root)} does not exist"]

    header = "\n".join(lock_path.read_text(encoding="utf-8").splitlines()[:15])
    if expected_header_substring not in header:
        errors.append(
            f"{lock_path.relative_to(repo_root)} is missing its expected header "
            f"({expected_header_substring!r}) in the first 15 lines -- hand-edited, or "
            f"generated by the wrong command?"
        )

    missing = sorted(direct_names(input_path) - set(locked_versions(lock_path)))
    if missing:
        errors.append(
            f"direct dependencies declared in {input_path.relative_to(repo_root)} but missing "
            f"from {lock_path.relative_to(repo_root)}: {missing}"
        )
    return errors


def check_cross_consistency(lock_a: Path, lock_b: Path) -> list[str]:
    versions_a, versions_b = locked_versions(lock_a), locked_versions(lock_b)
    errors = []
    for name in sorted(set(versions_a) & set(versions_b)):
        if versions_a[name] != versions_b[name]:
            errors.append(
                f"{name} is pinned to {versions_a[name]} in {lock_a.name} but "
                f"{versions_b[name]} in {lock_b.name}"
            )
    return errors


def main() -> int:
    errors: list[str] = []
    errors += check_pair(
        REPO_ROOT / "requirements.in", REPO_ROOT / "requirements.txt",
        expected_header_substring="do not hand-edit",
    )
    errors += check_pair(
        REPO_ROOT / "requirements-dev.in", REPO_ROOT / "requirements-dev.txt",
        expected_header_substring="autogenerated by pip-compile",
    )
    errors += check_cross_consistency(REPO_ROOT / "requirements.txt", REPO_ROOT / "requirements-dev.txt")

    if errors:
        print("Dependency consistency check FAILED:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    print("OK: requirements.in/.txt and requirements-dev.in/.txt are consistent.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
